apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: plugin
build:
  platforms: ["linux/amd64"]
  tagPolicy:
    sha256: {}
  artifacts:
    - image: ${IMAGE_REPOSITORY}/plugin
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
    - name: plugin
      chartPath: deploy/helm
      valuesFiles:
      - ${VALUES_LOCATION}/plugin.yaml